sonar.projectKey=<Sonar Cloud Project Key>
sonar.organization=synccomputingcode
sonar.language=python
sonar.python.version=3.8, 3.9, 3.10
# Limits to scripts directory. Defaults to . when missing.
# If using . (dot) you may want to set 
#sonar.coverage.exclusions=tests/**
sonar.source=scripts
sonar.python.coverage.reportPaths=coverage.xml
sonar.projectVersion=1.0
